version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mmasrb
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "56379:6379"
    volumes:
      - redisdata:/data

  predictor:
    build:
      context: ./services/predictor
      dockerfile: Dockerfile
    image: mmasrb-predictor:latest
    restart: unless-stopped
    environment:
      - UVICORN_WORKERS=1
    ports:
      - "8001:8001"

volumes:
  pgdata:
  redisdata:
